import { createHash } from 'node:crypto';

const START = '<!-- DIAGNOSTIC_BOOTSTRAP_START -->';
const END = '<!-- DIAGNOSTIC_BOOTSTRAP_END -->';
const BLOCK = /<!-- DIAGNOSTIC_BOOTSTRAP_START -->[\s\S]*?<!-- DIAGNOSTIC_BOOTSTRAP_END -->/;
const CONTRACT = 'js/diagnostics/diagnosticContract.js';
const COLLECTOR = 'js/diagnostics/bootstrapCollector.js';
const PAYLOAD = 'assets/generated/diagnostics/bootstrap-inline.js';
const MANIFEST = 'assets/generated/diagnostics/build-manifest.json';
const FOUNDATION = 'js/bundles/core-foundation.bundle.js';
const requiredResources = [
    'css/main.css', 'js/bundles/runtime-entry.bundle.js', FOUNDATION,
    'js/bundles/ui-shell.bundle.js', 'js/bundles/legacy-app.bundle.js'
];
const optionalResources = [
    'assets/vendor/three.min.js', 'assets/images/favicon.svg', 'assets/images/logo.svg',
    'css/heroui-bridge.css', 'css/theme-switcher-scroll.css', 'css/onboarding.css', 'css/vocab-reader.css',
    'assets/generated/listening-exams/manifest.js', 'assets/generated/listening-exams/listening-index.compat.js'
];
const digest = (text) => createHash('sha256').update(text).digest('hex');

function mapSections(content, paths, readSource) {
    return paths.map((source) => {
        const marker = `/* ===== ${source} ===== */\n`;
        const offset = content.indexOf(marker);
        if (offset < 0) throw new Error(`Missing source marker: ${source}`);
        const startLine = content.slice(0, offset + marker.length).split('\n').length;
        return { source, startLine, endLine: startLine + readSource(source).split('\n').length - 2, sourceStartLine: 1 };
    });
}

// All inputs are content-derived and project-relative. No Git/worktree paths, clock,
// cache query, environment variable, generated stamp or generated mapping enters identity.
export function buildDiagnosticArtifacts({ renderedBundles, bundleInputs, readSource }) {
    const index = readSource('index.html');
    if (!BLOCK.test(index)) throw new Error('Missing diagnostic bootstrap markers in index.html');
    const skeleton = index.replace(BLOCK, START + '\n' + END);
    const inputs = { ...renderedBundles, 'index.html': skeleton };
    for (const source of [CONTRACT, COLLECTOR, 'scripts/build-bundles.mjs', 'scripts/diagnostic-build.mjs',
        'developer/package.json', 'assets/vendor/three.min.js', 'assets/images/favicon.svg', 'assets/images/logo.svg',
        ...requiredResources.filter((value) => value.endsWith('.css')), ...optionalResources.filter((value) => value.endsWith('.css'))]) {
        inputs[source] = readSource(source);
    }
    const hashes = Object.keys(inputs).sort().map((path) => ({ path, sha256: digest(inputs[path]) }));
    const buildId = 'sha256:' + digest(JSON.stringify(hashes));
    const appVersion = JSON.parse(readSource('developer/package.json')).version;
    const metadata = { appVersion, buildId, mappingPath: MANIFEST };
    const stamp = `globalThis.AppDiagnosticBuild = Object.freeze(${JSON.stringify(metadata)});\n`;
    const payload = '/* Generated by scripts/build-bundles.mjs. Embed before external resources. */\n'
        + stamp + [CONTRACT, COLLECTOR].map((source) => `/* ===== ${source} ===== */\n${readSource(source)}`).join('\n');
    if (/<\/script/i.test(payload)) throw new Error('Unsafe closing script tag in bootstrap source');
    const mainHook = `globalThis.AppDiagnosticBootstrap.install(${JSON.stringify({ context: 'main', requiredResources, optionalResources })});`;
    const inline = `${START}\n<script>\n${payload}\n${mainHook}\n</script>\n        ${END}`;
    const generatedIndex = index.replace(BLOCK, () => inline);
    const stampedBundles = { ...renderedBundles, [FOUNDATION]: stamp + renderedBundles[FOUNDATION] };
    const mappings = Object.fromEntries(Object.entries(stampedBundles).map(([output, content]) =>
        [output, mapSections(content, bundleInputs[output], readSource)]));
    mappings[PAYLOAD] = mapSections(payload, [CONTRACT, COLLECTOR], readSource);
    mappings['index.html'] = mapSections(generatedIndex, [CONTRACT, COLLECTOR], readSource);
    const manifest = { schemaVersion: 1, ...metadata,
        identity: 'sha256 of sorted path/content-hash pairs; normalized unstamped bundles, bootstrap sources, entry skeleton, styles, vendor, images and build recipes',
        inputs: hashes, mappings };
    return { bundles: stampedBundles, generated: {
        'index.html': generatedIndex, [PAYLOAD]: payload, [MANIFEST]: JSON.stringify(manifest, null, 2) + '\n'
    }, metadata };
}
